// Package httphandler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httphandler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed   bool               `json:"completed"`
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// ListTodosParams defines parameters for ListTodos.
type ListTodosParams struct {
	PageSize  *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *string `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all todos
	// (GET /todos)
	ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams)
	// Create a new todo
	// (POST /todos)
	CreateTodo(w http.ResponseWriter, r *http.Request)
	// Delete a todo
	// (DELETE /todos/{todoID})
	DeleteTodo(w http.ResponseWriter, r *http.Request, todoID string)
	// Get a todo by ID
	// (GET /todos/{todoID})
	GetTodo(w http.ResponseWriter, r *http.Request, todoID string)
	// Update a todo
	// (PATCH /todos/{todoID})
	UpdateTodo(w http.ResponseWriter, r *http.Request, todoID string)
	// Complete a todo
	// (POST /todos/{todoID}:complete)
	CompleteTodo(w http.ResponseWriter, r *http.Request, todoID string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all todos
// (GET /todos)
func (_ Unimplemented) ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new todo
// (POST /todos)
func (_ Unimplemented) CreateTodo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a todo
// (DELETE /todos/{todoID})
func (_ Unimplemented) DeleteTodo(w http.ResponseWriter, r *http.Request, todoID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a todo by ID
// (GET /todos/{todoID})
func (_ Unimplemented) GetTodo(w http.ResponseWriter, r *http.Request, todoID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a todo
// (PATCH /todos/{todoID})
func (_ Unimplemented) UpdateTodo(w http.ResponseWriter, r *http.Request, todoID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete a todo
// (POST /todos/{todoID}:complete)
func (_ Unimplemented) CompleteTodo(w http.ResponseWriter, r *http.Request, todoID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTodosParams

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "pageToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageToken", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTodos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTodo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "todoID" -------------
	var todoID string

	err = runtime.BindStyledParameterWithOptions("simple", "todoID", chi.URLParam(r, "todoID"), &todoID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "todoID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTodo(w, r, todoID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "todoID" -------------
	var todoID string

	err = runtime.BindStyledParameterWithOptions("simple", "todoID", chi.URLParam(r, "todoID"), &todoID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "todoID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTodo(w, r, todoID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "todoID" -------------
	var todoID string

	err = runtime.BindStyledParameterWithOptions("simple", "todoID", chi.URLParam(r, "todoID"), &todoID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "todoID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTodo(w, r, todoID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTodo operation middleware
func (siw *ServerInterfaceWrapper) CompleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "todoID" -------------
	var todoID string

	err = runtime.BindStyledParameterWithOptions("simple", "todoID", chi.URLParam(r, "todoID"), &todoID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "todoID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTodo(w, r, todoID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/todos", wrapper.ListTodos)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/todos", wrapper.CreateTodo)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/todos/{todoID}", wrapper.DeleteTodo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/todos/{todoID}", wrapper.GetTodo)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/todos/{todoID}", wrapper.UpdateTodo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/todos/{todoID}:complete", wrapper.CompleteTodo)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWTW/jNhD9K8S0RzlSvYvFQrc0KQKjQVsk7qVBDow5tplQJEOOEriG/ntBUrZiSUka",
	"YI0ABiyL8/HmvZmht7AwlTUaNXkot+AXa6x4fDxzyAnnRpgrfKzRU3hpnbHoSGI0EegXTlqSRoeftLEI",
	"JXhyUq+gyYAkKRw5aTJw+FhLhwLKm9bsNtuZmbt7XFAIELIP0wbICik470PfGaOQ6+C0iMDFaQS8NK7i",
	"BCUITjghWSFkQ6DvFSLFQay6lmIszGv1ZlBb8TFMPYpSvhg+e1H/y2JfJhnj8u94eiw9e+nCK6mXZhAV",
	"TtnVb9fzZa1YgMJO/5qxpVHKPEu9YheGTYvpNzbTovbkNuyauBbcCX+yr7+EnSNk8ITOp7jBb1J8nRTf",
	"5kVRxs8/AbOxqLmVUMKXk+LkC2RgOa1juTkZYeLTCiMbgQsecM4ElHApPc2jRfBxvEJC56G82YIMGR9r",
	"dBvIQPMqoLJ8hdfy3yBQmqJU+5LXiqCcFnuOpCZcoQu0vR5pbh5QH4Tqc34bOsRbo30Sb1oUaTg0oY7l",
	"cGuVXMSC8nufNO3iScIqOv7scAkl/JR3qyBv90AeB7CTlzvHN0ndvqpKemJmyahlbI1cRLq2cCn1w2Hu",
	"Yf/MDXE1OTN1gj4w7UiL2X1dVdxtWpUYV6pN3GRgjR9Rs1tnkEYLPf1qxOZDnL1F1XBfNodTTK7GZiDa",
	"Lz8MQNJqqE0CJnqamJTjbV16XKdIjDONz5HvKF0ao3wbvmbnTWr7sJ+GIpzH93sRDoj4OtwVfxh21jJz",
	"CCTFYbwFkY0P8AXSeKri6Jz/+XsP8QVSC5fdbdjsPDbqyFIJy6nbBIlS6HfRO2vBclqsh3R0F8CRJmB4",
	"w/yvCfgENRLSff8Mm7jc3bHxkhxfKK1FS+ixxPx8snaFdnSFY3RPu1oP/cNmUUzgEypjK9TEkm34g+IU",
	"lLAmsmWeq2C3Np7K78X3Aprb5r8AAAD//22iblaNCgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
