// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ppzxc/golang-vibe-boilerplate/internal/adapter/eventbus"
	"github.com/ppzxc/golang-vibe-boilerplate/internal/adapter/httphandler"
	"github.com/ppzxc/golang-vibe-boilerplate/internal/adapter/postgresrepo"
	"github.com/ppzxc/golang-vibe-boilerplate/internal/app/todo"
	"github.com/ppzxc/golang-vibe-boilerplate/internal/config"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*Server, func(), error) {
	serverConfig := cfg.Server
	port := serverConfig.Port
	string2 := config.GetDSN(cfg)
	db, cleanup, err := postgresrepo.Open(string2)
	if err != nil {
		return nil, nil, err
	}
	todoRepository := postgresrepo.NewTodoRepository(db)
	inMemoryEventBus := eventbus.NewInMemoryEventBus()
	service := todo.NewService(todoRepository, inMemoryEventBus)
	handler := httphandler.NewRouter(service)
	server := NewServer(handler, port)
	return server, func() {
		cleanup()
	}, nil
}
